services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: bih-estimator-api
    env_file:
      - ./api/.env.template

    ports:
      - "8080:8080"
    restart: unless-stopped